name: flutter_weather
description: Using Flutter implement the Weather App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData,
  # Request Cancellation, File downloading, Timeout etc.
  # https://github.com/flutterchina/dio
  dio: ^1.0.9


  # dart中 json序列化 依赖
  # json_annotation
  # json_serializable
  # https://flutterchina.club/json
  # https://pub.dartlang.org/packages/json_serializable
  json_annotation: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # build_runner
  # The build_runner package provides a concrete way of generating files using Dart code,
  # outside of tools like pub. Unlike pub serve/build, files are always generated directly on disk,
  # and rebuilds are incremental - inspired by tools such as Bazel.
  # https://github.com/dart-lang/build
  build_runner: ^1.1.2

  # dart中 json序列化 依赖
  # json_annotation
  # json_serializable
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # image define
  assets:
    - assets/images/weather_icons/d00.png
    - assets/images/weather_icons/d01.png
    - assets/images/weather_icons/d03.png
    - assets/images/weather_icons/n00.png
    - assets/images/weather_icons/n01.png
    - assets/images/weather_icons/n03.png
    - assets/images/weather_icons/02.png
    - assets/images/weather_icons/04.png
    - assets/images/weather_icons/05.png
    - assets/images/weather_icons/06.png
    - assets/images/weather_icons/07.png
    - assets/images/weather_icons/08.png
    - assets/images/weather_icons/09.png
    - assets/images/weather_icons/10.png
    - assets/images/weather_icons/11.png
    - assets/images/weather_icons/12.png
    - assets/images/weather_icons/d13.png
    - assets/images/weather_icons/n13.png
    - assets/images/weather_icons/14.png
    - assets/images/weather_icons/15.png
    - assets/images/weather_icons/16.png
    - assets/images/weather_icons/17.png
    - assets/images/weather_icons/18.png
    - assets/images/weather_icons/19.png
    - assets/images/weather_icons/20.png
    - assets/images/weather_icons/21.png
    - assets/images/weather_icons/22.png
    - assets/images/weather_icons/23.png
    - assets/images/weather_icons/24.png
    - assets/images/weather_icons/25.png
    - assets/images/weather_icons/26.png
    - assets/images/weather_icons/27.png
    - assets/images/weather_icons/28.png
    - assets/images/weather_icons/29.png
    - assets/images/weather_icons/30.png
    - assets/images/weather_icons/31.png
    - assets/images/weather_icons/32.png
    - assets/images/weather_icons/49.png
    - assets/images/weather_icons/53.png
    - assets/images/weather_icons/54.png
    - assets/images/weather_icons/55.png
    - assets/images/weather_icons/56.png
    - assets/images/weather_icons/57.png
    - assets/images/weather_icons/58.png
    - assets/images/weather_icons/99.png
    - assets/images/weather_icons/301.png
    - assets/images/weather_icons/302.png

  # fonts define
  fonts:
    - family: Weather_IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
